version: "3.8"

services:
  app:
    build: ./app/
    command: sh -c "sleep 10s"
    depends_on:
      - mysql
    stdin_open: true
    tty: true

  mysql:
    image: mysql:8.1
    restart: always
    environment:
      - MYSQL_DATABASE=db
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - "3306:3306"
